import { TaskItem, UpcomingEvent, ProductivityTrendPoint, FocusCategoryPoint, NotificationItem } from './types';

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    title: 'Review quarterly product roadmap and sync with design lead',
    category: 'Product Quality',
    priority: 'High',
    status: 'To Do',
    dueTime: '10:30 AM',
    date: 'Today',
    aiConfidence: 96,
    notes: 'Focus on Q3 feature delivery priorities and UI polish for the LOOP assistant modal.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
  {
    id: 'task-2',
    title: 'Optimize API response payload for dashboard analytics endpoints',
    category: 'Shipping',
    priority: 'In Progress',
    status: 'In Progress',
    dueTime: '01:15 PM',
    date: 'Today',
    aiConfidence: 91,
    notes: 'Reduce bundle load time and implement server component caching.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
  {
    id: 'task-3',
    title: 'Analyze customer feedback sentiment score increase (+12% vs yesterday)',
    category: 'Customer Support',
    priority: 'Medium',
    status: 'To Do',
    dueTime: '03:00 PM',
    date: 'Today',
    aiConfidence: 89,
    notes: 'Check recent support tickets for shipping delay resolution patterns.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
  {
    id: 'task-4',
    title: 'Update subscription plan pricing matrix and tier comparisons',
    category: 'Pricing',
    priority: 'Medium',
    status: 'To Do',
    dueTime: '04:45 PM',
    date: 'Today',
    aiConfidence: 85,
    notes: 'Ensure enterprise tier reflects new custom AI feature bundle.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
  {
    id: 'task-5',
    title: 'Conduct 25-min Deep Focus Pomodoro block on bug fixes',
    category: 'Product Quality',
    priority: 'High',
    status: 'Done',
    dueTime: '09:00 AM',
    date: 'Today',
    aiConfidence: 98,
    notes: 'Completed morning focus session without distractions.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
  {
    id: 'task-6',
    title: 'Finalize Q2 AI executive summary report export',
    category: 'Returns',
    priority: 'Low',
    status: 'Done',
    dueTime: '08:30 AM',
    date: 'Today',
    aiConfidence: 94,
    notes: 'Exported PDF report for workspace leadership team.',
    assignedTo: 'Princy',
    workspace: 'Zidio Technologies',
  },
];

export const upcomingEvents: UpcomingEvent[] = [
  {
    id: 'evt-1',
    title: 'Sprint Planning & AI Insights Demo',
    time: '11:00 AM - 12:00 PM',
    date: 'Today',
    category: 'Team Sync',
    type: 'meeting',
  },
  {
    id: 'evt-2',
    title: 'Deep Work Focus Block (No Meetings)',
    time: '02:00 PM - 03:30 PM',
    date: 'Today',
    category: 'Focus',
    type: 'focus',
  },
  {
    id: 'evt-3',
    title: 'Q3 Enterprise Deployment Release',
    time: '05:00 PM',
    date: 'Tomorrow',
    category: 'Release',
    type: 'deadline',
  },
];

export const weeklyProductivityTrend: ProductivityTrendPoint[] = [
  { day: 'May 12', positive: 65, neutral: 25, focusScore: 78 },
  { day: 'May 13', positive: 72, neutral: 18, focusScore: 82 },
  { day: 'May 14', positive: 68, neutral: 22, focusScore: 80 },
  { day: 'May 15', positive: 85, neutral: 10, focusScore: 91 },
  { day: 'May 16', positive: 78, neutral: 15, focusScore: 86 },
  { day: 'May 17', positive: 90, neutral: 8, focusScore: 94 },
  { day: 'May 18', positive: 88, neutral: 9, focusScore: 92 },
];

export const focusCategories: FocusCategoryPoint[] = [
  { category: 'Shipping', percentage: 38, hours: 14.5, color: '#6C4CFD' },
  { category: 'Pricing', percentage: 24, hours: 9.2, color: '#8B5CF6' },
  { category: 'Customer Support', percentage: 18, hours: 6.8, color: '#3B82F6' },
  { category: 'Product Quality', percentage: 14, hours: 5.3, color: '#06B6D4' },
  { category: 'Returns', percentage: 6, hours: 2.3, color: '#EC4899' },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'AI Insight Available',
    description: 'Your morning focus score improved by +12%. Click to view details.',
    time: '10m ago',
    unread: true,
    type: 'ai',
  },
  {
    id: 'notif-2',
    title: 'Task Reminder',
    description: 'Review quarterly product roadmap is due at 10:30 AM.',
    time: '30m ago',
    unread: true,
    type: 'task',
  },
  {
    id: 'notif-3',
    title: 'Streak Milestone Unlocked 🔥',
    description: 'Congratulations! You reached a 7-day daily focus streak.',
    time: '2h ago',
    unread: false,
    type: 'reminder',
  },
];
